In [1]:
import numpy as np
import pandas as pd

In [12]:
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [13]:
df = pd.read_csv('../EDA/train.csv')[['Age', 'Fare', 'SibSp', 'Parch','Survived']]

In [14]:
df.dropna(inplace=True)

In [15]:
df['family'] = df['SibSp'] + df['Parch']

In [16]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [17]:
df.drop(columns=['SibSp', 'Parch'], inplace=True)

In [18]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 42)

In [21]:
clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy_score(y_pred, y_test)

0.6433566433566433

In [24]:
np.mean(cross_val_score(DecisionTreeClassifier(), X, y, cv=10, scoring="accuracy"))

0.6499413145539906

In [25]:
from sklearn.preprocessing import Binarizer

In [28]:
trf = ColumnTransformer([('trf1', Binarizer(copy=True),['family'])], remainder="passthrough")

In [29]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [30]:
pd.DataFrame(X_train_trf, columns=['family', 'age', 'Fare'])

     family   age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]